version: "3.8"

services:
  serverless:
    image: opklnm102/serverless:nikolaik-python-nodejs-python3.8-nodejs14-2.31.0
    env_file: ${ENVFILE:-.env}
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app
